# SPDX-FileCopyrightText: 2020 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

# Default values for juice-shop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

apiVersion: v2
replicaCount: 2

rollingUpdate: 
  maxUnavailable: 1                           
  maxSurge: 1

image:
  # image.repository -- Container Image containing the juice-shop
  repository: docker.io/bkimminich/juice-shop
  # image.tag -- The image tag
  # @default -- defaults to the appVersion
  tag: null
  pullPolicy: IfNotPresent

livenessProbe:
  enabled: true
  initialDelaySeconds: 5

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# -- add labels to the deployment, service and pods
labels: {}

# -- add annotations to the deployment, service and pods
annotations: {  
  prometheus.io/scrape: 'true',
 # prometheus.io/path: '/data/metrics',
 # prometheus.io/port: '3000'
  }

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  name: my-juice-shop
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations: {
    prometheus.io/scrape: 'true',
    kubernetes.io/ingress.class: nginx,
    #kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true",
    # specify the name of the global IP address resource to be associated with the HTTP(S) Load Balancer.
    #kubernetes.io/ingress.global-static-ip-name: demo ,
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt-prod ,
    # controls whether the ingress is modified ‘in-place’,
    # or a new one is created specifically for the HTTP01 challenge.
    #acme.cert-manager.io/http01-edit-in-place: "true"
     }
  hosts:
    - host: mambudemo.com
      paths:
        - /
  tls: 
    - secretName: demo-cert
      hosts:
        - mambudemo.com

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   #  limits:
    # cpu: 200m
   #  memory: 256Mi
   #requests:
  #   cpu: 200m
  #   memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
